version: '3'

x-common-node-service: &common-node-service
  image: node:19-alpine
  entrypoint: ./entrypoint.sh
  working_dir: /app

services:
  client:
    <<: *common-node-service
    container_name: "GuessTheThing_Dev_Client"
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.GuessTheThing_client.rule=Host(`guessthething.localhost`)"
      - "traefik.http.services.GuessTheThing_client.loadbalancer.server.port=3000"

  server:
    <<: *common-node-service
    container_name: "GuessTheThing_Dev_Server"
    volumes:
      - ./server/:/app
    ports:
      - "3001:3001"
    labels:
      - "traefik.http.routers.GuessTheThing_server.rule=Host(`api.guessthething.localhost`)"
      - "traefik.http.services.GuessTheThing_server.loadbalancer.server.port=3001"

  traefik:
    image: traefik:v3.0
    container_name: "GuessTheThing_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock