version: '3'

services:
  client:
    container_name: "GuessTheThing_client"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    labels:
      - "traefik.http.routers.GuessTheThing_client.rule=Host(`guessthething.localhost`)"
      - "traefik.http.services.GuessTheThing_client.loadbalancer.server.port=3000"

  server:
    container_name: "GuessTheThing_server"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    labels:
      - "traefik.http.routers.GuessTheThing_server.rule=Host(`api.guessthething.localhost`)"
      - "traefik.http.services.GuessTheThing_server.loadbalancer.server.port=3001"
      
  traefik:
    image: traefik:v3.0
    container_name: "GuessTheThing_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock